### ISSUE TITLE
get error when running node-file-manager command

### ISSUE THREAD

**Issue by Andrewyg** [efeiefei/node-file-manager#21]
<img width="960" alt="2017-05-28" src="https://cloud.githubusercontent.com/assets/20808546/26528201/6429f608-43d8-11e7-8d20-72c451d2578b.png">

**Comment by efeiefei** [comment]
@Andrewyg Sorry, windows cannot use command `node-file-manager` directly.
You can do it like this:
```
  git clone https://github.com/efeiefei/node-file-manager.git
  cd node-file-manager
  npm i
  cd lib
  node --harmony index.js -p 8080 -d /path/to
```
