### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by danolife** [efeiefei/node-file-manager#28]
Hello!

I am using your file manager in order to browse through files and download them from my server.
I would like to suggest just a couple of improvements:
- Display disk usage
- Display recursive size for directories (include the size of the files in that directory recursively) instead of always displaying 4KB

Would you prefer that I write a pull request, or would a fork be better?

Thanks
Dany

**Comment by danolife** [comment]
FYI, I forked your repo and implemented above improvements.
See https://github.com/danolife/node-file-manager

**Comment by efeiefei** [comment]
Sorry to replay so late. I haven't check email recently.
Look forward to your PR. But it may be expensive to calculate recursive
size.

Best,
efei


Dany Badr <notifications@github.com> 于2018年7月12日周四 下午8:45写道：
