### ISSUE TITLE
Encoding problem with special caracters in directory names

### ISSUE THREAD

**Issue by f0i** [efeiefei/node-file-manager#5]
Links inside a directory with umlauts (äöü) are not working.

Example:

```
mkdir -p umlaut/ä/test
node-file-manager -p 8080 -d $PWD
```

Now you can navigate to `umlaut/ä/` but `umlaut/ä/test` will return `Error: 404Path Not Exists!` because the path is URL-encoded twice (`%25C3%25A4` instead of `%C3%A4`)

**Comment by efeiefei** [comment]
Now, it is ok
@f0i
