### ISSUE TITLE
Deploy to Web App?

### ISSUE THREAD

**Issue by sameerkhoja** [efeiefei/node-file-manager#9]
Hi,

I absolutely love this application! I was wondering if this concept could be extended to a standalone webapp, just as a place to upload and download files that are stored in a database. How would one go about developing such an app? Thank you in advance!

Best,
Sameer

**Comment by efeiefei** [comment]
This is a very simple project based on `file system`. But move files to database is also simple, just modified `fileManager.js` will be ok.
@samkho10
